variables:
  azureSubscription: AZR-RWD-PRD1
  docker.imageName: eventdispatcher
  acr.azureContainerRegistryName: prdrwdinfac1401
  acr.repositoryName: eventdispatcherrepository
  serviceName: PRDRWDWEBFA1401
